version: "3"

services:
  registry:
    container_name: registry
    image: registry:2
    restart: always
    expose:
      - 5000
    # ports:
    #   - "5000:5000"
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ./dockeregistry/auth:/auth
      - ./dockeregistry/data:/data
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    links:
      - resgistry
